language: python
sudo: false
python:
  - 3.5
  - 3.6
#  - 3.7
# See https://github.com/travis-ci/travis-ci/issues/9815
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
script:
  - python --version
  - python setup.py build
  - python setup.py test
  - python -m pip install autodoc docutils numpydoc Sphinx
  - make -C docs html
  - python -m pip install setuptools twine wheel
  - python setup.py sdist bdist_wheel
