language: python
sudo: false
python:
  - 3.5
  - 3.6
#  - 3.7
# See https://github.com/travis-ci/travis-ci/issues/9815
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
script:
  - python --version
  - python -m unittest
